name: Build & Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    # Avoid duplicate runs when pull requests are opened from the same repo
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install package
        run: pip install -e .[dev,docs]

      - name: Install make
        run: sudo apt update && sudo apt -y --no-install-recommends install make

      - name: Lint
        run: make lint ARGS=--check

      - name: Check manifest
        run: check-manifest

      - name: Mypy
        run: make mypy

      - name: Pull images
        run: docker compose pull keycloak tox

      - name: Test
        run: make test

      - name: Build
        run: make build

      - name: Test docs
        run: make docs-test

      - name: Build docs
        run: make docs

      - name: CodeCov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: derlin/mantelo
          files: .artifacts/coverage.xml
          disable_search: true
          # Put a plugin we don't use, to ensure it doesn't try
          # to generate its own coverage.xml using the pycoverage plugin
          plugins: xcode
          verbose: true

      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: .artifacts/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: |
            dist/*.*
            docs/_build/html
            docs/_build/doctest
