name: weekly check

on:
  workflow_dispatch:
  schedule:
    # Sunday at midnight
    - cron: "0 0 * * 0"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install package
        run: pip install -e .[dev]

      - name: Install make
        run: sudo apt update && sudo apt -y --no-install-recommends install make

      - name: Test
        run: make test

      - name: Docs test
        run: make docs-test
